### ISSUE TITLE
Can't add event from traffic light view if so events present in resource

### ISSUE THREAD

**Issue by traviscosgrave** [futurice/meeting-room-tablet#12]
I had a fresh resource calendar with zero events. The Book Now button an the traffic light screen was doing nothing. Looking at the code, it seems as if there is no event, then the time range is returned as null and the button handler returns without doing anything.

[Line 121 of Room.java](https://github.com/futurice/meeting-room-tablet/blob/master/android/Reservator/src/com/futurice/android/reservator/model/Room.java#L121)

**Comment by bklang** [comment]
I believe this can be closed, as it was fixed in #14. Not sure if/when a new build will get to the Play store. Maybe @Wisheri knows?

**Comment by Wisheri** [comment]
Yeah, this can be closed. I will release the new build and close this issue when it's done.

**Comment by Wisheri** [comment]
The new build is now in the Play store.
