### ISSUE TITLE
Option "only use resource calendars" doesn't work

### ISSUE THREAD

**Issue by hypn00o** [futurice/meeting-room-tablet#64]
When launching the app if you select option "only use resource calendars" from the second setup screen, it doesn't let you proceed. It let's you proceed only by choosing your own calendar. Similarly, if you choose your own calendar and then try to access "ALL ROOMS" it lists just your own and if you try to change option "If this option is enabled, non-resource calendars will be shown" from settings, no calendars are shown at all (tried to refresh as well).

**Comment by hypn00o** [comment]
Magically it started to work today 👍

**Comment by pedpess** [comment]
@hypn00o Great to hear. We currently are not with due time to give the support to this repo, but if there are some more errors let us know.
